language: python

python:
  - "3.7" #Versión estable
  - "3.7-dev" #Version de desarrollo

before_install:
  - python --version
  - pip install -U pip
  - pip install nose

install:
  - pip install -r requirements.txt


script:
    - make tests
